services:
  # ================= BACKEND =================
  - type: web
    name: nail-studio-backend
    runtime: node
    plan: free

    rootDir: backend   # 🔥 IMPORTANT

    buildCommand: npm install
    startCommand: npm start

    healthCheckPath: /health

    envVars:
      - key: NODE_ENV
        value: production

      # ❌ DO NOT SET PORT (Render handles it)


      - key: CORS_ORIGIN
        value: https://nail-studio-frontend.onrender.com

      - key: ACCESS_TOKEN_SECRET
        sync: false

      - key: REFRESH_TOKEN_SECRET
        sync: false

      - key: ACCESS_TOKEN_TTL
        value: 15m

      - key: REFRESH_TOKEN_TTL
        value: 7d

      - key: REFRESH_COOKIE_NAME
        value: rt

      - key: UPLOAD_DIR
        value: uploads


  # ================= FRONTEND =================
  - type: web
    name: nail-studio-frontend
    runtime: static
    plan: free

    rootDir: frontend   # 🔥 IMPORTANT

    buildCommand: npm install && npm run build
    staticPublishPath: dist

    routes:
      - type: rewrite
        source: /*
        destination: /index.html

    envVars:
      - key: VITE_API_URL
        value: https://nail-studio-backend.onrender.com
